# Generated by Django 3.1 on 2020-08-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0002_auto_20200812_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Ruby', 'Ruby'), ('Python Application', 'Python Application'), ('Node.js', 'Node.js'), ('Flask', 'Flask'), ('Uncategorized', 'Uncategorized'), ('Django', 'Django')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Uncategorized'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('React.js', 'React.js'), ('Angular.js', 'Angular.js'), ('Uncategorized', 'Uncategorized'), ('Vue.js', 'Vue.js')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
