# Generated by Django 3.1 on 2020-08-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0003_auto_20200814_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Node.js', 'Node.js'), ('Uncategorized', 'Uncategorized'), ('Python Application', 'Python Application'), ('Ruby', 'Ruby')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('Vue.js', 'Vue.js'), ('Angular.js', 'Angular.js'), ('React.js', 'React.js'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
