# Generated by Django 3.1 on 2020-08-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0005_auto_20200815_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Ruby', 'Ruby'), ('Python Application', 'Python Application'), ('Node.js', 'Node.js'), ('Flask', 'Flask'), ('Django', 'Django'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('React.js', 'React.js'), ('Vue.js', 'Vue.js'), ('Angular.js', 'Angular.js'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
