# Generated by Django 3.1 on 2020-08-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0007_auto_20200815_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Uncategorized', 'Uncategorized'), ('Python Application', 'Python Application'), ('Ruby', 'Ruby'), ('Node.js', 'Node.js')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('Angular.js', 'Angular.js'), ('Vue.js', 'Vue.js'), ('Uncategorized', 'Uncategorized'), ('React.js', 'React.js')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
