# Generated by Django 3.1 on 2020-08-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0008_auto_20200815_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Node.js', 'Node.js'), ('Ruby', 'Ruby'), ('Uncategorized', 'Uncategorized'), ('Django', 'Django'), ('Flask', 'Flask'), ('Python Application', 'Python Application')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('React.js', 'React.js'), ('Vue.js', 'Vue.js'), ('Angular.js', 'Angular.js'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
