# Generated by Django 3.1 on 2020-08-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0009_auto_20200815_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repository',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_server',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('Uncategorized', 'Uncategorized'), ('Flask', 'Flask'), ('Ruby', 'Ruby'), ('Python Application', 'Python Application'), ('Node.js', 'Node.js')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('Angular.js', 'Angular.js'), ('React.js', 'React.js'), ('Uncategorized', 'Uncategorized'), ('Vue.js', 'Vue.js')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
