# Generated by Django 3.1 on 2020-08-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0010_auto_20200815_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Ruby', 'Ruby'), ('Python Application', 'Python Application'), ('Flask', 'Flask'), ('Node.js', 'Node.js'), ('Uncategorized', 'Uncategorized'), ('Django', 'Django')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('Angular.js', 'Angular.js'), ('Uncategorized', 'Uncategorized'), ('React.js', 'React.js'), ('Vue.js', 'Vue.js')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
