# Generated by Django 3.1 on 2021-04-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0014_auto_20210416_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinformation',
            name='what_are_my_technical_skills',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='what_is_my_personality',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='who_am_i',
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='first_section_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='first_section_header',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='second_section_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='second_section_header',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='third_section_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='third_section_header',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Flask', 'Flask'), ('Ruby', 'Ruby'), ('Python Application', 'Python Application'), ('Django', 'Django'), ('Node.js', 'Node.js'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
