# Generated by Django 3.1 on 2021-04-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0016_auto_20210429_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Flask', 'Flask'), ('Ruby', 'Ruby'), ('Python Application', 'Python Application'), ('Uncategorized', 'Uncategorized'), ('Node.js', 'Node.js'), ('Django', 'Django')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('React.js', 'React.js'), ('Uncategorized', 'Uncategorized'), ('Angular.js', 'Angular.js'), ('Vue.js', 'Vue.js')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
