# Generated by Django 3.1 on 2021-04-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0018_auto_20210429_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Node.js', 'Node.js'), ('Ruby', 'Ruby'), ('Django', 'Django'), ('Flask', 'Flask'), ('Uncategorized', 'Uncategorized'), ('Python Application', 'Python Application')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('Angular.js', 'Angular.js'), ('Vue.js', 'Vue.js'), ('Uncategorized', 'Uncategorized'), ('React.js', 'React.js')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
